"""database init

Revision ID: 01a0d3c3848a
Revises: 
Create Date: 2026-07-13 22:03:19.490170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '01a0d3c3848a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sys_permission',
    sa.Column('menu_id', sa.BigInteger(), nullable=False, comment='所属菜单ID'),
    sa.Column('name', sa.String(length=64), nullable=False, comment='权限名称'),
    sa.Column('code', sa.String(length=128), nullable=False, comment='权限标识'),
    sa.Column('type', mysql.TINYINT(), nullable=False, comment='权限类型：0=按钮 1=接口'),
    sa.Column('description', sa.String(length=255), nullable=True, comment='权限描述'),
    sa.Column('sort', sa.Integer(), nullable=False, comment='排序'),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sys_permission')),
    sa.UniqueConstraint('code', name=op.f('uq_sys_permission_code')),
    comment='权限表'
    )
    op.add_column('sys_menu', sa.Column('description', sa.String(length=255), nullable=True, comment='菜单说明'))
    op.drop_column('sys_menu', 'desc')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sys_menu', sa.Column('desc', mysql.VARCHAR(length=255), nullable=True, comment='菜单说明'))
    op.drop_column('sys_menu', 'description')
    op.drop_table('sys_permission')
    # ### end Alembic commands ###
