"""init openadmin tables

Revision ID: 10e658082e61
Revises: 000000000001
Create Date: 2026-09-05 17:39:11.461605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = '10e658082e61'
down_revision: Union[str, Sequence[str], None] = '000000000001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sys_dept',
    sa.Column('parent_id', sa.BigInteger(), nullable=False, comment='上级部门ID（0=顶级）'),
    sa.Column('dept_name', sa.String(length=50), nullable=False, comment='部门名称'),
    sa.Column('sort', sa.Integer(), nullable=False, comment='显示顺序（越小越靠前）'),
    sa.Column('status', sa.SMALLINT(), nullable=False, comment='状态 0=启用 1=禁用'),
    sa.Column('create_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sys_dept')),
    comment='部门表'
    )
    op.create_index(op.f('ix_sys_dept_parent_id'), 'sys_dept', ['parent_id'], unique=False)
    op.create_table('sys_login_log',
    sa.Column('trace_id', sa.String(length=64), nullable=False, comment='链路追踪ID'),
    sa.Column('user_id', sa.BigInteger(), nullable=True, comment='用户ID'),
    sa.Column('username', sa.String(length=50), nullable=False, comment='用户名称'),
    sa.Column('response_code', sa.String(length=32), nullable=True, comment='响应码'),
    sa.Column('response_msg', sa.String(length=512), nullable=True, comment='响应信息/错误描述'),
    sa.Column('client_ip', sa.String(length=50), nullable=False, comment='客户端IP'),
    sa.Column('ip_country', sa.String(length=32), nullable=True, comment='国家'),
    sa.Column('ip_province', sa.String(length=32), nullable=True, comment='省份/直辖市'),
    sa.Column('ip_city', sa.String(length=32), nullable=True, comment='城市'),
    sa.Column('os', sa.String(length=30), nullable=True, comment='操作系统'),
    sa.Column('browser', sa.String(length=100), nullable=True, comment='浏览器'),
    sa.Column('user_agent', sa.String(length=512), nullable=True, comment='客户端标识'),
    sa.Column('create_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sys_login_log')),
    comment='系统用户登录日志表'
    )
    op.create_table('sys_menu',
    sa.Column('name', sa.String(length=128), nullable=False, comment='菜单唯一标识（程序使用：路由名/权限编码，全局不可重复）'),
    sa.Column('label', sa.String(length=128), nullable=False, comment='菜单展示名称（前端页面显示给用户看，可中文，允许重复）'),
    sa.Column('parent_id', sa.BigInteger(), nullable=False, comment='父菜单ID'),
    sa.Column('sort', sa.Integer(), nullable=False, comment='排序'),
    sa.Column('path', sa.String(length=255), nullable=False, comment='前端路由地址'),
    sa.Column('component', sa.String(length=255), nullable=True, comment='前端组件路径'),
    sa.Column('type', sa.SMALLINT(), nullable=False, comment='菜单类型：0=目录 1=页面'),
    sa.Column('description', sa.String(length=255), nullable=True, comment='菜单说明'),
    sa.Column('icon', sa.String(length=128), nullable=False, comment='菜单图标'),
    sa.Column('is_hidden', sa.SMALLINT(), nullable=False, comment='是否隐藏：0=显示 1=隐藏'),
    sa.Column('is_frame', sa.SMALLINT(), nullable=False, comment='是否内嵌：0=否 1=是'),
    sa.Column('is_external', sa.SMALLINT(), nullable=False, comment='是否外部链接：0=否 1=是'),
    sa.Column('status', sa.SMALLINT(), nullable=False, comment='状态：0=启用 1=禁用'),
    sa.Column('create_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sys_menu')),
    sa.UniqueConstraint('name', name=op.f('uq_sys_menu_name')),
    comment='菜单表(目录+页面)'
    )
    op.create_table('sys_oper_log',
    sa.Column('trace_id', sa.String(length=64), nullable=False, comment='分布式链路追踪ID'),
    sa.Column('request_method', sa.String(length=16), nullable=False, comment='HTTP请求方法'),
    sa.Column('api_path', sa.String(length=255), nullable=False, comment='API接口路径'),
    sa.Column('api_name', sa.String(length=128), nullable=True, comment='API接口名称'),
    sa.Column('module', sa.String(length=64), nullable=True, comment='所属业务模块'),
    sa.Column('operator_id', sa.String(length=64), nullable=True, comment='操作员ID'),
    sa.Column('client_ip', sa.String(length=46), nullable=False, comment='客户端IP（兼容IPv6）'),
    sa.Column('ip_country', sa.String(length=32), nullable=True, comment='国家'),
    sa.Column('ip_province', sa.String(length=32), nullable=True, comment='省份/直辖市'),
    sa.Column('ip_city', sa.String(length=32), nullable=True, comment='城市'),
    sa.Column('cost_time', sa.Integer(), nullable=False, comment='请求耗时（毫秒）'),
    sa.Column('response_code', sa.String(length=32), nullable=True, comment='响应码'),
    sa.Column('response_msg', sa.String(length=512), nullable=True, comment='响应信息/错误描述'),
    sa.Column('response_data', sa.JSON(none_as_null=True), nullable=True, comment='响应数据'),
    sa.Column('path_params', sa.JSON(none_as_null=True), nullable=True, comment='路径参数（如/api/user/{id}中的id）'),
    sa.Column('query_params', sa.JSON(none_as_null=True), nullable=True, comment='查询参数（如/api/user?name=test中的name）'),
    sa.Column('request_body', sa.JSON(none_as_null=True), nullable=True, comment='POST/PUT请求体数据'),
    sa.Column('create_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sys_oper_log')),
    comment='系统操作日志表'
    )
    op.create_index(op.f('ix_sys_oper_log_api_path'), 'sys_oper_log', ['api_path'], unique=False)
    op.create_index(op.f('ix_sys_oper_log_trace_id'), 'sys_oper_log', ['trace_id'], unique=False)
    op.create_table('sys_permission',
    sa.Column('menu_id', sa.BigInteger(), nullable=False, comment='所属菜单ID'),
    sa.Column('name', sa.String(length=64), nullable=False, comment='权限名称'),
    sa.Column('code', sa.String(length=128), nullable=False, comment='权限标识'),
    sa.Column('description', sa.String(length=255), nullable=True, comment='权限描述'),
    sa.Column('sort', sa.Integer(), nullable=False, comment='排序'),
    sa.Column('status', sa.SMALLINT(), nullable=False, comment='状态：0=正常 1=停用'),
    sa.Column('create_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sys_permission')),
    sa.UniqueConstraint('code', name=op.f('uq_sys_permission_code')),
    comment='权限表'
    )
    op.create_table('sys_post',
    sa.Column('post_name', sa.String(length=50), nullable=False, comment='岗位名称'),
    sa.Column('dept_id', sa.BigInteger(), nullable=True, comment='所属部门ID（可为空）'),
    sa.Column('sort', sa.Integer(), nullable=False, comment='显示顺序（越小越靠前）'),
    sa.Column('status', sa.SMALLINT(), nullable=False, comment='状态 0=启用 1=禁用'),
    sa.Column('remark', sa.String(length=255), nullable=False, comment='备注'),
    sa.Column('create_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sys_post')),
    comment='岗位表'
    )
    op.create_index(op.f('ix_sys_post_dept_id'), 'sys_post', ['dept_id'], unique=False)
    op.create_table('sys_post_role',
    sa.Column('post_id', sa.BigInteger(), nullable=False, comment='岗位ID'),
    sa.Column('role_id', sa.BigInteger(), nullable=False, comment='角色ID'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sys_post_role')),
    sa.UniqueConstraint('post_id', 'role_id', name='uk_post_role'),
    comment='岗位-角色关联表'
    )
    op.create_table('sys_role',
    sa.Column('role_name', sa.String(length=50), nullable=False, comment='角色名称'),
    sa.Column('role_code', sa.String(length=50), nullable=False, comment='角色唯一编码'),
    sa.Column('sort', sa.Integer(), nullable=False, comment='显示顺序（越小越靠前）'),
    sa.Column('description', sa.String(length=255), nullable=True, comment='角色描述'),
    sa.Column('status', sa.SMALLINT(), nullable=False, comment='状态 0=启用 1=禁用'),
    sa.Column('create_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sys_role')),
    comment='角色表'
    )
    op.create_index(op.f('ix_sys_role_role_code'), 'sys_role', ['role_code'], unique=True)
    op.create_table('sys_role_permission',
    sa.Column('role_id', sa.BigInteger(), nullable=False, comment='角色ID'),
    sa.Column('perm_id', sa.BigInteger(), nullable=False, comment='权限ID'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sys_role_permission')),
    sa.UniqueConstraint('role_id', 'perm_id', name='uk_role_perm'),
    comment='角色-权限关联表'
    )
    op.create_table('sys_user',
    sa.Column('username', sa.String(length=50), nullable=False, comment='登录账号（唯一）'),
    sa.Column('employee_no', sa.String(length=12), nullable=True, comment='工号（唯一）'),
    sa.Column('password', sa.String(length=100), nullable=False, comment='登录密码（加密存储）'),
    sa.Column('nickname', sa.String(length=50), nullable=True, comment='用户昵称/姓名'),
    sa.Column('avatar', sa.String(length=255), nullable=True, comment='头像URL'),
    sa.Column('email', sa.String(length=100), nullable=True, comment='邮箱'),
    sa.Column('phone', sa.String(length=20), nullable=True, comment='手机号'),
    sa.Column('sex', sa.SMALLINT(), nullable=False, comment='性别：0=未知 1=男 2=女'),
    sa.Column('status', sa.SMALLINT(), nullable=False, comment='账号状态：0=正常 1=禁用 2=锁定 3=注销 4=冻结'),
    sa.Column('dept_id', sa.BigInteger(), nullable=True, comment='所属部门ID'),
    sa.Column('last_login_ip', sa.String(length=50), nullable=True, comment='最后登录IP'),
    sa.Column('last_login_date', sa.DateTime(timezone=True), nullable=True, comment='最后登录时间'),
    sa.Column('login_fail_count', sa.Integer(), nullable=False, comment='连续登录失败次数'),
    sa.Column('lock_time', sa.DateTime(timezone=True), nullable=True, comment='账号锁定时间'),
    sa.Column('remark', sa.String(length=500), nullable=True, comment='备注'),
    sa.Column('del_flag', sa.SMALLINT(), nullable=False, comment='删除标志：0=未删除 1=已删除'),
    sa.Column('is_superuser', sa.Boolean(), nullable=False, comment='是否超级管理员'),
    sa.Column('face_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=512), nullable=True, comment='人脸512维特征向量，NULL表示未录入人脸'),
    sa.Column('create_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sys_user')),
    sa.UniqueConstraint('email', name=op.f('uq_sys_user_email')),
    sa.UniqueConstraint('phone', name=op.f('uq_sys_user_phone')),
    sa.UniqueConstraint('username', name=op.f('uq_sys_user_username')),
    comment='用户表'
    )
    op.create_index(op.f('ix_sys_user_dept_id'), 'sys_user', ['dept_id'], unique=False)
    op.create_index(op.f('ix_sys_user_employee_no'), 'sys_user', ['employee_no'], unique=True)
    op.create_table('sys_user_post',
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='用户ID'),
    sa.Column('post_id', sa.BigInteger(), nullable=False, comment='岗位ID'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sys_user_post')),
    sa.UniqueConstraint('user_id', 'post_id', name='uk_user_post'),
    comment='用户-岗位关联表'
    )
    op.create_table('sys_user_role',
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='用户ID'),
    sa.Column('role_id', sa.BigInteger(), nullable=False, comment='角色ID'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sys_user_role')),
    sa.UniqueConstraint('user_id', 'role_id', name='uk_user_role'),
    comment='用户-角色关联表'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sys_user_role')
    op.drop_table('sys_user_post')
    op.drop_index(op.f('ix_sys_user_employee_no'), table_name='sys_user')
    op.drop_index(op.f('ix_sys_user_dept_id'), table_name='sys_user')
    op.drop_table('sys_user')
    op.drop_table('sys_role_permission')
    op.drop_index(op.f('ix_sys_role_role_code'), table_name='sys_role')
    op.drop_table('sys_role')
    op.drop_table('sys_post_role')
    op.drop_index(op.f('ix_sys_post_dept_id'), table_name='sys_post')
    op.drop_table('sys_post')
    op.drop_table('sys_permission')
    op.drop_index(op.f('ix_sys_oper_log_trace_id'), table_name='sys_oper_log')
    op.drop_index(op.f('ix_sys_oper_log_api_path'), table_name='sys_oper_log')
    op.drop_table('sys_oper_log')
    op.drop_table('sys_menu')
    op.drop_table('sys_login_log')
    op.drop_index(op.f('ix_sys_dept_parent_id'), table_name='sys_dept')
    op.drop_table('sys_dept')
    # ### end Alembic commands ###
