"""add sys_login_log sys_operator_log table

Revision ID: 1aec0e50e916
Revises: c9de948371ed
Create Date: 2026-05-16 18:14:17.545204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1aec0e50e916'
down_revision: Union[str, Sequence[str], None] = 'c9de948371ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sys_login_log', sa.Column('response_code', sa.String(length=32), nullable=True, comment='响应码'))
    op.add_column('sys_login_log', sa.Column('response_msg', sa.String(length=512), nullable=True, comment='响应信息/错误描述'))
    op.add_column('sys_login_log', sa.Column('os', sa.String(length=30), nullable=True, comment='操作系统'))
    op.add_column('sys_login_log', sa.Column('user_agent', sa.String(length=512), nullable=True, comment='客户端标识'))
    op.alter_column('sys_login_log', 'username',
               existing_type=mysql.VARCHAR(length=50),
               comment='用户名称',
               existing_comment='登录账号',
               existing_nullable=False)
    op.drop_column('sys_login_log', 'operate_time')
    op.drop_column('sys_login_log', 'device_type')
    op.drop_column('sys_login_log', 'login_type')
    op.drop_column('sys_login_log', 'ip_location')
    op.drop_column('sys_login_log', 'operate_status')
    op.drop_column('sys_login_log', 'fail_reason')
    op.drop_column('sys_login_log', 'operate_type')
    op.add_column('sys_oper_log', sa.Column('path_params', sa.JSON(none_as_null=True), nullable=True, comment='路径参数（如/api/user/{id}中的id）'))
    op.add_column('sys_oper_log', sa.Column('query_params', sa.JSON(none_as_null=True), nullable=True, comment='查询参数（如/api/user?name=test中的name）'))
    op.add_column('sys_oper_log', sa.Column('request_body', sa.JSON(none_as_null=True), nullable=True, comment='POST/PUT请求体数据'))
    op.drop_column('sys_oper_log', 'ip_location')
    op.drop_column('sys_oper_log', 'user_agent')
    op.drop_column('sys_oper_log', 'terminal_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sys_oper_log', sa.Column('terminal_type', mysql.VARCHAR(length=32), nullable=True, comment='终端类型'))
    op.add_column('sys_oper_log', sa.Column('user_agent', mysql.VARCHAR(length=512), nullable=True, comment='客户端标识'))
    op.add_column('sys_oper_log', sa.Column('ip_location', mysql.VARCHAR(length=128), nullable=True, comment='完整属地(展示用：国家-省-市)'))
    op.drop_column('sys_oper_log', 'request_body')
    op.drop_column('sys_oper_log', 'query_params')
    op.drop_column('sys_oper_log', 'path_params')
    op.add_column('sys_login_log', sa.Column('operate_type', mysql.TINYINT(), autoincrement=False, nullable=False, comment='操作类型 1-登录 2-登出'))
    op.add_column('sys_login_log', sa.Column('fail_reason', mysql.VARCHAR(length=255), nullable=True, comment='失败原因'))
    op.add_column('sys_login_log', sa.Column('operate_status', mysql.TINYINT(), autoincrement=False, nullable=False, comment='状态 0-失败 1-成功'))
    op.add_column('sys_login_log', sa.Column('ip_location', mysql.VARCHAR(length=128), nullable=True, comment='完整属地：国家-省-市'))
    op.add_column('sys_login_log', sa.Column('login_type', mysql.TINYINT(), autoincrement=False, nullable=True, comment='登录类型 1-账号密码 2-短信 3-第三方 4-扫码 5-单点（登出时为NULL）'))
    op.add_column('sys_login_log', sa.Column('device_type', mysql.VARCHAR(length=30), nullable=True, comment='设备类型'))
    op.add_column('sys_login_log', sa.Column('operate_time', mysql.DATETIME(), nullable=False, comment='操作时间'))
    op.alter_column('sys_login_log', 'username',
               existing_type=mysql.VARCHAR(length=50),
               comment='登录账号',
               existing_comment='用户名称',
               existing_nullable=False)
    op.drop_column('sys_login_log', 'user_agent')
    op.drop_column('sys_login_log', 'os')
    op.drop_column('sys_login_log', 'response_msg')
    op.drop_column('sys_login_log', 'response_code')
    # ### end Alembic commands ###
