"""新增用户注册申请表

Revision ID: 1bb6e285160b
Revises: 3087cc584724
Create Date: 2026-09-29 15:26:11.809752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = '1bb6e285160b'
down_revision: Union[str, Sequence[str], None] = '3087cc584724'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sys_user_apply',
    sa.Column('username', sa.String(length=50), nullable=False, comment='申请登录账号'),
    sa.Column('password', sa.String(length=100), nullable=False, comment='登录密码（加密存储）'),
    sa.Column('phone', sa.String(length=20), nullable=False, comment='手机号'),
    sa.Column('status', sa.SMALLINT(), nullable=False, comment='审核状态：0=待审核 1=已通过 2=已拒绝 3=撤销'),
    sa.Column('audit_user_id', sa.BigInteger(), nullable=False, comment='审批管理员ID'),
    sa.Column('audit_time', sa.DateTime(timezone=True), nullable=False, comment='审批时间'),
    sa.Column('audit_reason', sa.String(length=500), nullable=True, comment='审批意见/拒绝原因'),
    sa.Column('del_flag', sa.SMALLINT(), nullable=False, comment='删除标志：0=正常 1=删除'),
    sa.Column('create_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sys_user_apply')),
    comment='用户注册申请表'
    )
    op.create_index(op.f('ix_sys_user_apply_audit_user_id'), 'sys_user_apply', ['audit_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sys_user_apply_audit_user_id'), table_name='sys_user_apply')
    op.drop_table('sys_user_apply')
    # ### end Alembic commands ###
