"""create face hnsw indx

Revision ID: 3087cc584724
Revises: 10e658082e61
Create Date: 2026-09-05 20:11:10.199533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = '3087cc584724'
down_revision: Union[str, Sequence[str], None] = '10e658082e61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_sys_user_face_embedding_hnsw', 'sys_user', ['face_embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'face_embedding': 'vector_cosine_ops'}, postgresql_where=sa.text('face_embedding IS NOT NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sys_user_face_embedding_hnsw', table_name='sys_user', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'face_embedding': 'vector_cosine_ops'}, postgresql_where=sa.text('face_embedding IS NOT NULL'))
    # ### end Alembic commands ###
