"""新增用户注册申请表

Revision ID: 480c6b314cd6
Revises: 1bb6e285160b
Create Date: 2026-09-29 16:37:01.102497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '480c6b314cd6'
down_revision: Union[str, Sequence[str], None] = '1bb6e285160b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sys_user_apply', 'audit_user_id',
               existing_type=sa.BIGINT(),
               nullable=True,
               existing_comment='审批管理员ID')
    op.alter_column('sys_user_apply', 'audit_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_comment='审批时间')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sys_user_apply', 'audit_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_comment='审批时间')
    op.alter_column('sys_user_apply', 'audit_user_id',
               existing_type=sa.BIGINT(),
               nullable=False,
               existing_comment='审批管理员ID')
    # ### end Alembic commands ###
