"""sys_user表手机号和邮箱添加唯一约束

Revision ID: 4de58a447cee
Revises: d6eac606fec3
Create Date: 2026-04-27 10:47:44.078378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4de58a447cee'
down_revision: Union[str, Sequence[str], None] = 'd6eac606fec3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_sys_user_email'), 'sys_user', ['email'])
    op.create_unique_constraint(op.f('uq_sys_user_phone'), 'sys_user', ['phone'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_sys_user_phone'), 'sys_user', type_='unique')
    op.drop_constraint(op.f('uq_sys_user_email'), 'sys_user', type_='unique')
    # ### end Alembic commands ###
