"""table sys_permission add status field

Revision ID: 5a7b71235342
Revises: 01a0d3c3848a
Create Date: 2026-07-28 12:04:49.844363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5a7b71235342'
down_revision: Union[str, Sequence[str], None] = '01a0d3c3848a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_sys_oper_log_create_time'), table_name='sys_oper_log')
    op.add_column('sys_permission', sa.Column('status', mysql.TINYINT(), nullable=False, comment='状态：0=正常 1=停用'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sys_permission', 'status')
    op.create_index(op.f('idx_sys_oper_log_create_time'), 'sys_oper_log', ['create_time'], unique=False)
    # ### end Alembic commands ###
