"""add sys_login_log sys_operator_log table

Revision ID: 623f5b01fadb
Revises: d3d1e9dea12f
Create Date: 2026-05-15 17:30:51.264768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '623f5b01fadb'
down_revision: Union[str, Sequence[str], None] = 'd3d1e9dea12f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sys_login_log', sa.Column('ip_country', sa.String(length=32), nullable=True, comment='国家'))
    op.add_column('sys_login_log', sa.Column('ip_province', sa.String(length=32), nullable=True, comment='省份/直辖市'))
    op.add_column('sys_login_log', sa.Column('ip_city', sa.String(length=32), nullable=True, comment='城市'))
    op.add_column('sys_login_log', sa.Column('ip_location', sa.String(length=128), nullable=True, comment='完整属地(展示用：国家-省-市)'))
    op.add_column('sys_operator_log', sa.Column('ip_country', sa.String(length=32), nullable=True, comment='国家'))
    op.add_column('sys_operator_log', sa.Column('ip_province', sa.String(length=32), nullable=True, comment='省份/直辖市'))
    op.add_column('sys_operator_log', sa.Column('ip_city', sa.String(length=32), nullable=True, comment='城市'))
    op.add_column('sys_operator_log', sa.Column('ip_location', sa.String(length=128), nullable=True, comment='完整属地(展示用：国家-省-市)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sys_operator_log', 'ip_location')
    op.drop_column('sys_operator_log', 'ip_city')
    op.drop_column('sys_operator_log', 'ip_province')
    op.drop_column('sys_operator_log', 'ip_country')
    op.drop_column('sys_login_log', 'ip_location')
    op.drop_column('sys_login_log', 'ip_city')
    op.drop_column('sys_login_log', 'ip_province')
    op.drop_column('sys_login_log', 'ip_country')
    # ### end Alembic commands ###
