"""init table

Revision ID: 83d3611b9008
Revises: 
Create Date: 2026-05-02 00:00:08.715271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '83d3611b9008'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sys_dept',
    sa.Column('parent_id', sa.BigInteger(), nullable=False, comment='上级部门ID（0=顶级）'),
    sa.Column('dept_name', sa.String(length=50), nullable=False, comment='部门名称'),
    sa.Column('sort', sa.Integer(), nullable=False, comment='显示顺序（越小越靠前）'),
    sa.Column('status', mysql.TINYINT(), nullable=False, comment='状态 0=启用 1=禁用'),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sys_dept')),
    comment='部门表'
    )
    op.create_index(op.f('ix_sys_dept_parent_id'), 'sys_dept', ['parent_id'], unique=False)
    op.create_table('sys_permission',
    sa.Column('parent_id', sa.BigInteger(), nullable=False, comment='父菜单ID'),
    sa.Column('perm_type', sa.String(length=20), nullable=False, comment='权限类型：menu=菜单 button=按钮'),
    sa.Column('perm_code', sa.String(length=100), nullable=False, comment='权限标识'),
    sa.Column('perm_name', sa.String(length=100), nullable=False, comment='名称'),
    sa.Column('path', sa.String(length=255), nullable=True, comment='路由地址'),
    sa.Column('component', sa.String(length=255), nullable=True, comment='前端组件'),
    sa.Column('icon', sa.String(length=100), nullable=True, comment='菜单图标'),
    sa.Column('sort', sa.Integer(), nullable=False, comment='显示顺序'),
    sa.Column('status', mysql.TINYINT(), nullable=False, comment='状态 0=启用 1=禁用'),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sys_permission')),
    comment='权限表'
    )
    op.create_index(op.f('ix_sys_permission_perm_code'), 'sys_permission', ['perm_code'], unique=True)
    op.create_index(op.f('ix_sys_permission_perm_type'), 'sys_permission', ['perm_type'], unique=False)
    op.create_table('sys_post',
    sa.Column('post_name', sa.String(length=50), nullable=False, comment='岗位名称'),
    sa.Column('dept_id', sa.BigInteger(), nullable=True, comment='所属部门ID（可为空）'),
    sa.Column('sort', sa.Integer(), nullable=False, comment='显示顺序（越小越靠前）'),
    sa.Column('status', mysql.TINYINT(), nullable=False, comment='状态 0=启用 1=禁用'),
    sa.Column('remark', sa.String(length=255), nullable=False, comment='备注'),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sys_post')),
    comment='岗位表'
    )
    op.create_index(op.f('ix_sys_post_dept_id'), 'sys_post', ['dept_id'], unique=False)
    op.create_table('sys_post_role',
    sa.Column('post_id', sa.BigInteger(), nullable=False, comment='岗位ID'),
    sa.Column('role_id', sa.BigInteger(), nullable=False, comment='角色ID'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sys_post_role')),
    sa.UniqueConstraint('post_id', 'role_id', name='uk_post_role'),
    comment='岗位-角色关联表'
    )
    op.create_table('sys_role',
    sa.Column('role_name', sa.String(length=50), nullable=False, comment='角色名称'),
    sa.Column('role_code', sa.String(length=50), nullable=False, comment='角色唯一编码'),
    sa.Column('sort', sa.Integer(), nullable=False, comment='显示顺序（越小越靠前）'),
    sa.Column('description', sa.String(length=255), nullable=True, comment='角色描述'),
    sa.Column('status', mysql.TINYINT(), nullable=False, comment='状态 0=启用 1=禁用'),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sys_role')),
    comment='角色表'
    )
    op.create_index(op.f('ix_sys_role_role_code'), 'sys_role', ['role_code'], unique=True)
    op.create_table('sys_role_permission',
    sa.Column('role_id', sa.BigInteger(), nullable=False, comment='角色ID'),
    sa.Column('perm_id', sa.BigInteger(), nullable=False, comment='权限ID'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sys_role_permission')),
    sa.UniqueConstraint('role_id', 'perm_id', name='uk_role_perm'),
    comment='角色-权限关联表'
    )
    op.create_table('sys_user',
    sa.Column('username', sa.String(length=50), nullable=False, comment='登录账号（唯一）'),
    sa.Column('employee_no', sa.String(length=12), nullable=True, comment='工号（唯一）'),
    sa.Column('password', sa.String(length=100), nullable=False, comment='登录密码（加密存储）'),
    sa.Column('nickname', sa.String(length=50), nullable=True, comment='用户昵称/姓名'),
    sa.Column('avatar', sa.String(length=255), nullable=True, comment='头像URL'),
    sa.Column('email', sa.String(length=100), nullable=True, comment='邮箱'),
    sa.Column('phone', sa.String(length=20), nullable=True, comment='手机号'),
    sa.Column('sex', mysql.TINYINT(), nullable=False, comment='性别：0=未知 1=男 2=女'),
    sa.Column('status', mysql.TINYINT(), nullable=False, comment='账号状态：0=正常 1=禁用 2=锁定 3=注销 4=冻结'),
    sa.Column('dept_id', sa.BigInteger(), nullable=True, comment='所属部门ID'),
    sa.Column('last_login_ip', sa.String(length=50), nullable=True, comment='最后登录IP'),
    sa.Column('last_login_date', sa.DateTime(), nullable=True, comment='最后登录时间'),
    sa.Column('login_fail_count', sa.Integer(), nullable=False, comment='连续登录失败次数'),
    sa.Column('lock_time', sa.DateTime(), nullable=True, comment='账号锁定时间'),
    sa.Column('remark', sa.String(length=500), nullable=True, comment='备注'),
    sa.Column('del_flag', mysql.TINYINT(), nullable=False, comment='删除标志：0=未删除 1=已删除'),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sys_user')),
    sa.UniqueConstraint('email', name=op.f('uq_sys_user_email')),
    sa.UniqueConstraint('phone', name=op.f('uq_sys_user_phone')),
    sa.UniqueConstraint('username', name=op.f('uq_sys_user_username')),
    comment='用户表'
    )
    op.create_index(op.f('ix_sys_user_dept_id'), 'sys_user', ['dept_id'], unique=False)
    op.create_index(op.f('ix_sys_user_employee_no'), 'sys_user', ['employee_no'], unique=True)
    op.create_table('sys_user_post',
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='用户ID'),
    sa.Column('post_id', sa.BigInteger(), nullable=False, comment='岗位ID'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sys_user_post')),
    sa.UniqueConstraint('user_id', 'post_id', name='uk_user_post'),
    comment='用户-岗位关联表'
    )
    op.create_table('sys_user_role',
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='用户ID'),
    sa.Column('role_id', sa.BigInteger(), nullable=False, comment='角色ID'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sys_user_role')),
    sa.UniqueConstraint('user_id', 'role_id', name='uk_user_role'),
    comment='用户-角色关联表'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sys_user_role')
    op.drop_table('sys_user_post')
    op.drop_index(op.f('ix_sys_user_employee_no'), table_name='sys_user')
    op.drop_index(op.f('ix_sys_user_dept_id'), table_name='sys_user')
    op.drop_table('sys_user')
    op.drop_table('sys_role_permission')
    op.drop_index(op.f('ix_sys_role_role_code'), table_name='sys_role')
    op.drop_table('sys_role')
    op.drop_table('sys_post_role')
    op.drop_index(op.f('ix_sys_post_dept_id'), table_name='sys_post')
    op.drop_table('sys_post')
    op.drop_index(op.f('ix_sys_permission_perm_type'), table_name='sys_permission')
    op.drop_index(op.f('ix_sys_permission_perm_code'), table_name='sys_permission')
    op.drop_table('sys_permission')
    op.drop_index(op.f('ix_sys_dept_parent_id'), table_name='sys_dept')
    op.drop_table('sys_dept')
    # ### end Alembic commands ###
