"""add sys_login_log table

Revision ID: 87d6ca337ad1
Revises: 623f5b01fadb
Create Date: 2026-05-16 15:40:11.982463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '87d6ca337ad1'
down_revision: Union[str, Sequence[str], None] = '623f5b01fadb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sys_login_log', sa.Column('operate_status', mysql.TINYINT(), nullable=False, comment='状态 0-失败 1-成功'))
    op.add_column('sys_login_log', sa.Column('client_ip', sa.String(length=50), nullable=False, comment='客户端IP'))
    op.add_column('sys_login_log', sa.Column('browser', sa.String(length=100), nullable=True, comment='浏览器'))
    op.add_column('sys_login_log', sa.Column('trace_id', sa.String(length=64), nullable=True, comment='链路追踪ID'))
    op.alter_column('sys_login_log', 'username',
               existing_type=mysql.VARCHAR(length=64),
               type_=sa.String(length=50),
               comment='登录账号',
               existing_comment='登录账号（手机号/邮箱/用户名）',
               existing_nullable=False)
    op.alter_column('sys_login_log', 'login_type',
               existing_type=mysql.TINYINT(),
               nullable=True,
               comment='登录类型 1-账号密码 2-短信 3-第三方 4-扫码 5-单点（登出时为NULL）',
               existing_comment='登录类型：1-账号密码 2-短信 3-第三方 4-扫码 5-邮箱')
    op.alter_column('sys_login_log', 'operate_type',
               existing_type=mysql.TINYINT(),
               comment='操作类型 1-登录 2-登出',
               existing_comment='操作类型：1-登录 2-登出',
               existing_nullable=False)
    op.alter_column('sys_login_log', 'ip_location',
               existing_type=mysql.VARCHAR(length=128),
               comment='完整属地：国家-省-市',
               existing_comment='完整属地(展示用：国家-省-市)',
               existing_nullable=True)
    op.alter_column('sys_login_log', 'device_type',
               existing_type=mysql.TINYINT(),
               type_=sa.String(length=30),
               comment='设备类型',
               existing_comment='设备：0-未知 1-PC 2-移动端 3-平板',
               existing_nullable=True)
    op.alter_column('sys_login_log', 'operate_time',
               existing_type=mysql.DATETIME(),
               comment='操作时间',
               existing_comment='操作时间（登录/登出时间）',
               existing_nullable=False)
    op.drop_index(op.f('ix_sys_login_log_user_id'), table_name='sys_login_log')
    op.create_table_comment(
        'sys_login_log',
        '系统用户登录日志表',
        existing_comment='系统登录日志表',
        schema=None
    )
    op.drop_column('sys_login_log', 'login_status')
    op.drop_column('sys_login_log', 'remark')
    op.drop_column('sys_login_log', 'os_name')
    op.drop_column('sys_login_log', 'browser_name')
    op.drop_column('sys_login_log', 'login_ip')
    op.drop_column('sys_login_log', 'user_agent')
    op.drop_column('sys_login_log', 'login_location')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sys_login_log', sa.Column('login_location', mysql.VARCHAR(length=128), nullable=True, comment='登录地点'))
    op.add_column('sys_login_log', sa.Column('user_agent', mysql.VARCHAR(length=512), nullable=True, comment='UA信息'))
    op.add_column('sys_login_log', sa.Column('login_ip', mysql.VARCHAR(length=45), nullable=False, comment='IP地址'))
    op.add_column('sys_login_log', sa.Column('browser_name', mysql.VARCHAR(length=64), nullable=True, comment='浏览器'))
    op.add_column('sys_login_log', sa.Column('os_name', mysql.VARCHAR(length=64), nullable=True, comment='操作系统'))
    op.add_column('sys_login_log', sa.Column('remark', mysql.VARCHAR(length=500), nullable=True, comment='备注'))
    op.add_column('sys_login_log', sa.Column('login_status', mysql.TINYINT(), autoincrement=False, nullable=False, comment='状态：0-成功 1-失败'))
    op.create_table_comment(
        'sys_login_log',
        '系统登录日志表',
        existing_comment='系统用户登录日志表',
        schema=None
    )
    op.create_index(op.f('ix_sys_login_log_user_id'), 'sys_login_log', ['user_id'], unique=False)
    op.alter_column('sys_login_log', 'operate_time',
               existing_type=mysql.DATETIME(),
               comment='操作时间（登录/登出时间）',
               existing_comment='操作时间',
               existing_nullable=False)
    op.alter_column('sys_login_log', 'device_type',
               existing_type=sa.String(length=30),
               type_=mysql.TINYINT(),
               comment='设备：0-未知 1-PC 2-移动端 3-平板',
               existing_comment='设备类型',
               existing_nullable=True)
    op.alter_column('sys_login_log', 'ip_location',
               existing_type=mysql.VARCHAR(length=128),
               comment='完整属地(展示用：国家-省-市)',
               existing_comment='完整属地：国家-省-市',
               existing_nullable=True)
    op.alter_column('sys_login_log', 'operate_type',
               existing_type=mysql.TINYINT(),
               comment='操作类型：1-登录 2-登出',
               existing_comment='操作类型 1-登录 2-登出',
               existing_nullable=False)
    op.alter_column('sys_login_log', 'login_type',
               existing_type=mysql.TINYINT(),
               nullable=False,
               comment='登录类型：1-账号密码 2-短信 3-第三方 4-扫码 5-邮箱',
               existing_comment='登录类型 1-账号密码 2-短信 3-第三方 4-扫码 5-单点（登出时为NULL）')
    op.alter_column('sys_login_log', 'username',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=64),
               comment='登录账号（手机号/邮箱/用户名）',
               existing_comment='登录账号',
               existing_nullable=False)
    op.drop_column('sys_login_log', 'trace_id')
    op.drop_column('sys_login_log', 'browser')
    op.drop_column('sys_login_log', 'client_ip')
    op.drop_column('sys_login_log', 'operate_status')
    # ### end Alembic commands ###
