"""alter table menu structure

Revision ID: 9d5ea40f6934
Revises: d0b785f77ff6
Create Date: 2026-07-11 23:24:12.848863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9d5ea40f6934'
down_revision: Union[str, Sequence[str], None] = 'd0b785f77ff6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sys_menu', sa.Column('type', mysql.TINYINT(), nullable=False, comment='菜单类型：0=目录 1=页面'))
    op.add_column('sys_menu', sa.Column('desc', sa.String(length=255), nullable=True, comment='菜单说明'))
    op.drop_column('sys_menu', 'menu_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sys_menu', sa.Column('menu_type', mysql.TINYINT(), autoincrement=False, nullable=False, comment='菜单类型：0=目录 1=页面'))
    op.drop_column('sys_menu', 'desc')
    op.drop_column('sys_menu', 'type')
    # ### end Alembic commands ###
