"""add sys_login_log sys_operator_log table

Revision ID: c9de948371ed
Revises: 87d6ca337ad1
Create Date: 2026-05-16 16:33:27.664323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c9de948371ed'
down_revision: Union[str, Sequence[str], None] = '87d6ca337ad1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sys_login_log',
    sa.Column('user_id', sa.BigInteger(), nullable=True, comment='用户ID'),
    sa.Column('username', sa.String(length=50), nullable=False, comment='登录账号'),
    sa.Column('login_type', mysql.TINYINT(), nullable=True, comment='登录类型 1-账号密码 2-短信 3-第三方 4-扫码 5-单点（登出时为NULL）'),
    sa.Column('operate_type', mysql.TINYINT(), nullable=False, comment='操作类型 1-登录 2-登出'),
    sa.Column('operate_status', mysql.TINYINT(), nullable=False, comment='状态 0-失败 1-成功'),
    sa.Column('fail_reason', sa.String(length=255), nullable=True, comment='失败原因'),
    sa.Column('client_ip', sa.String(length=50), nullable=False, comment='客户端IP'),
    sa.Column('ip_country', sa.String(length=32), nullable=True, comment='国家'),
    sa.Column('ip_province', sa.String(length=32), nullable=True, comment='省份/直辖市'),
    sa.Column('ip_city', sa.String(length=32), nullable=True, comment='城市'),
    sa.Column('ip_location', sa.String(length=128), nullable=True, comment='完整属地：国家-省-市'),
    sa.Column('device_type', sa.String(length=30), nullable=True, comment='设备类型'),
    sa.Column('browser', sa.String(length=100), nullable=True, comment='浏览器'),
    sa.Column('trace_id', sa.String(length=64), nullable=False, comment='链路追踪ID'),
    sa.Column('operate_time', sa.DateTime(), nullable=False, comment='操作时间'),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sys_login_log')),
    comment='系统用户登录日志表'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sys_login_log')
    # ### end Alembic commands ###
