"""add sys_oper_log table

Revision ID: cb4aef49a898
Revises: d6deb8b1e85e
Create Date: 2026-05-16 20:38:15.281210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb4aef49a898'
down_revision: Union[str, Sequence[str], None] = 'd6deb8b1e85e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sys_oper_log', sa.Column('response_msg', sa.String(length=512), nullable=True, comment='响应信息/错误描述'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sys_oper_log', 'response_msg')
    # ### end Alembic commands ###
