"""openadmin database init

Revision ID: d0b785f77ff6
Revises: 
Create Date: 2026-07-11 23:15:57.960146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd0b785f77ff6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sys_menu',
    sa.Column('name', sa.String(length=128), nullable=False, comment='菜单唯一标识（程序使用：路由名/权限编码，全局不可重复）'),
    sa.Column('label', sa.String(length=128), nullable=False, comment='菜单展示名称（前端页面显示给用户看，可中文，允许重复）'),
    sa.Column('parent_id', sa.BigInteger(), nullable=False, comment='父菜单ID'),
    sa.Column('sort', sa.Integer(), nullable=False, comment='排序'),
    sa.Column('path', sa.String(length=255), nullable=False, comment='前端路由地址'),
    sa.Column('component', sa.String(length=255), nullable=True, comment='前端组件路径'),
    sa.Column('menu_type', mysql.TINYINT(), nullable=False, comment='菜单类型：0=目录 1=页面'),
    sa.Column('icon', sa.String(length=128), nullable=False, comment='菜单图标'),
    sa.Column('is_hidden', mysql.TINYINT(), nullable=False, comment='是否隐藏：0=显示 1=隐藏'),
    sa.Column('is_frame', mysql.TINYINT(), nullable=False, comment='是否内嵌：0=否 1=是'),
    sa.Column('is_external', mysql.TINYINT(), nullable=False, comment='是否外部链接：0=否 1=是'),
    sa.Column('status', mysql.TINYINT(), nullable=False, comment='状态：0=启用 1=禁用'),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sys_menu')),
    sa.UniqueConstraint('name', name=op.f('uq_sys_menu_name')),
    comment='菜单表(目录+页面)'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sys_menu')
    # ### end Alembic commands ###
