"""sys_user 表增加是否超级管理员字段 is_superuser

Revision ID: d0e02c7b2af5
Revises: 83d3611b9008
Create Date: 2026-05-02 16:15:03.329879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0e02c7b2af5'
down_revision: Union[str, Sequence[str], None] = '83d3611b9008'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sys_user', sa.Column('is_superuser', sa.Boolean(), nullable=False, comment='是否超级管理员'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sys_user', 'is_superuser')
    # ### end Alembic commands ###
