"""add sys_login_log table

Revision ID: d3d1e9dea12f
Revises: a015c7b78102
Create Date: 2026-05-08 09:46:20.055553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd3d1e9dea12f'
down_revision: Union[str, Sequence[str], None] = 'a015c7b78102'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sys_login_log',
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='用户ID'),
    sa.Column('username', sa.String(length=64), nullable=False, comment='登录账号（手机号/邮箱/用户名）'),
    sa.Column('operate_type', mysql.TINYINT(), nullable=False, comment='操作类型：1-登录 2-登出'),
    sa.Column('login_type', mysql.TINYINT(), nullable=False, comment='登录类型：1-账号密码 2-短信 3-第三方 4-扫码 5-邮箱'),
    sa.Column('login_status', mysql.TINYINT(), nullable=False, comment='状态：0-成功 1-失败'),
    sa.Column('fail_reason', sa.String(length=255), nullable=True, comment='失败原因'),
    sa.Column('login_ip', sa.String(length=45), nullable=False, comment='IP地址'),
    sa.Column('login_location', sa.String(length=128), nullable=True, comment='登录地点'),
    sa.Column('device_type', mysql.TINYINT(), nullable=True, comment='设备：0-未知 1-PC 2-移动端 3-平板'),
    sa.Column('os_name', sa.String(length=64), nullable=True, comment='操作系统'),
    sa.Column('browser_name', sa.String(length=64), nullable=True, comment='浏览器'),
    sa.Column('user_agent', sa.String(length=512), nullable=True, comment='UA信息'),
    sa.Column('operate_time', sa.DateTime(), nullable=False, comment='操作时间（登录/登出时间）'),
    sa.Column('remark', sa.String(length=500), nullable=True, comment='备注'),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sys_login_log')),
    comment='系统登录日志表'
    )
    op.create_index(op.f('ix_sys_login_log_user_id'), 'sys_login_log', ['user_id'], unique=False)
    op.drop_index(op.f('uk_role_menu'), table_name='sys_role_menu')
    op.drop_table('sys_role_menu')
    op.add_column('sys_menu', sa.Column('status', mysql.TINYINT(), nullable=False, comment='状态：0=启用 1=禁用'))
    op.alter_column('sys_permission', 'perm_type',
               existing_type=mysql.TINYINT(),
               comment='权限类型：0=按钮 1=接口',
               existing_comment='权限类型：1=按钮 2=接口',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sys_permission', 'perm_type',
               existing_type=mysql.TINYINT(),
               comment='权限类型：1=按钮 2=接口',
               existing_comment='权限类型：0=按钮 1=接口',
               existing_nullable=False)
    op.drop_column('sys_menu', 'status')
    op.create_table('sys_role_menu',
    sa.Column('role_id', mysql.BIGINT(), autoincrement=False, nullable=False, comment='角色ID'),
    sa.Column('menu_id', mysql.BIGINT(), autoincrement=False, nullable=False, comment='菜单ID'),
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.PrimaryKeyConstraint('id'),
    comment='角色-菜单关联表',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_comment='角色-菜单关联表',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('uk_role_menu'), 'sys_role_menu', ['role_id', 'menu_id'], unique=True)
    op.drop_index(op.f('ix_sys_login_log_user_id'), table_name='sys_login_log')
    op.drop_table('sys_login_log')
    # ### end Alembic commands ###
