"""add sys_oper_log table

Revision ID: d6deb8b1e85e
Revises: 1aec0e50e916
Create Date: 2026-05-16 20:25:29.488731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd6deb8b1e85e'
down_revision: Union[str, Sequence[str], None] = '1aec0e50e916'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sys_oper_log', sa.Column('response_data', sa.JSON(none_as_null=True), nullable=True, comment='响应数据'))
    op.drop_column('sys_oper_log', 'response_msg')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sys_oper_log', sa.Column('response_msg', mysql.VARCHAR(length=512), nullable=True, comment='响应信息/错误描述'))
    op.drop_column('sys_oper_log', 'response_data')
    # ### end Alembic commands ###
