"""init users table

Revision ID: d6eac606fec3
Revises: eafae89e20e3
Create Date: 2026-04-27 10:43:44.645800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd6eac606fec3'
down_revision: Union[str, Sequence[str], None] = 'eafae89e20e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sys_user', sa.Column('password', sa.String(length=100), nullable=False, comment='登录密码（加密存储）'))
    op.add_column('sys_user', sa.Column('nickname', sa.String(length=50), nullable=True, comment='用户昵称/姓名'))
    op.add_column('sys_user', sa.Column('avatar', sa.String(length=255), nullable=True, comment='头像URL'))
    op.add_column('sys_user', sa.Column('phone', sa.String(length=20), nullable=True, comment='手机号'))
    op.add_column('sys_user', sa.Column('sex', mysql.TINYINT(), nullable=False, comment='性别：0=未知 1=男 2=女'))
    op.add_column('sys_user', sa.Column('status', mysql.TINYINT(), nullable=False, comment='账号状态：0=禁用 1=正常 2-锁定'))
    op.add_column('sys_user', sa.Column('dept_id', sa.BigInteger(), nullable=True, comment='所属部门ID'))
    op.add_column('sys_user', sa.Column('post_id', sa.BigInteger(), nullable=True, comment='所属岗位ID'))
    op.add_column('sys_user', sa.Column('last_login_ip', sa.String(length=50), nullable=True, comment='最后登录IP'))
    op.add_column('sys_user', sa.Column('last_login_date', sa.DateTime(), nullable=True, comment='最后登录时间'))
    op.add_column('sys_user', sa.Column('login_fail_count', sa.Integer(), nullable=False, comment='连续登录失败次数'))
    op.add_column('sys_user', sa.Column('lock_time', sa.DateTime(), nullable=True, comment='账号锁定时间'))
    op.add_column('sys_user', sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'))
    op.add_column('sys_user', sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'))
    op.add_column('sys_user', sa.Column('remark', sa.String(length=500), nullable=True, comment='备注'))
    op.add_column('sys_user', sa.Column('del_flag', mysql.TINYINT(), nullable=False, comment='删除标志：0=未删除 1=已删除'))
    op.alter_column('sys_user', 'id',
               existing_type=mysql.INTEGER(),
               type_=sa.BigInteger(),
               comment='用户ID（主键）',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('sys_user', 'username',
               existing_type=mysql.VARCHAR(length=50),
               comment='登录账号（唯一）',
               existing_nullable=False)
    op.alter_column('sys_user', 'email',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True,
               comment='邮箱')
    op.drop_index(op.f('ix_sys_user_email'), table_name='sys_user')
    op.drop_index(op.f('ix_sys_user_id'), table_name='sys_user')
    op.drop_index(op.f('ix_sys_user_username'), table_name='sys_user')
    op.create_unique_constraint(op.f('uq_sys_user_username'), 'sys_user', ['username'])
    op.drop_column('sys_user', 'password_hash')
    op.drop_column('sys_user', 'created_at')
    op.drop_column('sys_user', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sys_user', sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=False))
    op.add_column('sys_user', sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=False))
    op.add_column('sys_user', sa.Column('password_hash', mysql.VARCHAR(length=255), nullable=False))
    op.drop_constraint(op.f('uq_sys_user_username'), 'sys_user', type_='unique')
    op.create_index(op.f('ix_sys_user_username'), 'sys_user', ['username'], unique=True)
    op.create_index(op.f('ix_sys_user_id'), 'sys_user', ['id'], unique=False)
    op.create_index(op.f('ix_sys_user_email'), 'sys_user', ['email'], unique=True)
    op.alter_column('sys_user', 'email',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False,
               comment=None,
               existing_comment='邮箱')
    op.alter_column('sys_user', 'username',
               existing_type=mysql.VARCHAR(length=50),
               comment=None,
               existing_comment='登录账号（唯一）',
               existing_nullable=False)
    op.alter_column('sys_user', 'id',
               existing_type=sa.BigInteger(),
               type_=mysql.INTEGER(),
               comment=None,
               existing_comment='用户ID（主键）',
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('sys_user', 'del_flag')
    op.drop_column('sys_user', 'remark')
    op.drop_column('sys_user', 'update_time')
    op.drop_column('sys_user', 'create_time')
    op.drop_column('sys_user', 'lock_time')
    op.drop_column('sys_user', 'login_fail_count')
    op.drop_column('sys_user', 'last_login_date')
    op.drop_column('sys_user', 'last_login_ip')
    op.drop_column('sys_user', 'post_id')
    op.drop_column('sys_user', 'dept_id')
    op.drop_column('sys_user', 'status')
    op.drop_column('sys_user', 'sex')
    op.drop_column('sys_user', 'phone')
    op.drop_column('sys_user', 'avatar')
    op.drop_column('sys_user', 'nickname')
    op.drop_column('sys_user', 'password')
    # ### end Alembic commands ###
