"""初始化表结构

Revision ID: eafae89e20e3
Revises: 
Create Date: 2026-04-20 15:50:45.393687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eafae89e20e3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sys_user',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='用户ID（主键）'),
    sa.Column('username', sa.String(length=50), nullable=False, comment='登录账号（唯一）'),
    sa.Column('password', sa.String(length=100), nullable=False, comment='登录密码（加密存储）'),
    sa.Column('nickname', sa.String(length=50), nullable=True, comment='用户昵称/姓名'),
    sa.Column('avatar', sa.String(length=255), nullable=True, comment='头像URL'),
    sa.Column('email', sa.String(length=100), nullable=True, comment='邮箱'),
    sa.Column('phone', sa.String(length=20), nullable=True, comment='手机号'),
    sa.Column('sex', sa.SmallInteger(), server_default='0', comment='性别：0=未知 1=男 2=女'),
    sa.Column('status', sa.SmallInteger(), server_default='1', nullable=False, comment='账号状态：0=禁用 1=正常 2-锁定'),
    sa.Column('dept_id', sa.BigInteger(), nullable=True, comment='所属部门ID'),
    sa.Column('post_id', sa.BigInteger(), nullable=True, comment='所属岗位ID'),
    sa.Column('last_login_ip', sa.String(length=50), nullable=True, comment='最后登录IP'),
    sa.Column('last_login_date', sa.DateTime(), nullable=True, comment='最后登录时间'),
    sa.Column('login_fail_count', sa.Integer(), server_default='0', comment='连续登录失败次数'),
    sa.Column('lock_time', sa.DateTime(), nullable=True, comment='账号锁定时间'),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.Column('remark', sa.String(length=500), nullable=True, comment='备注'),
    sa.Column('del_flag', sa.SmallInteger(), server_default='0', nullable=False, comment='删除标志：0=未删除 1=已删除'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone'),
    comment='后台用户表'
    )
    op.create_index(op.f('ix_sys_user_username'), 'sys_user', ['username'], unique=True)
    op.create_index(op.f('ix_sys_user_email'), 'sys_user', ['email'], unique=True)
    op.create_index(op.f('ix_sys_user_phone'), 'sys_user', ['phone'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sys_user_phone'), table_name='sys_user')
    op.drop_index(op.f('ix_sys_user_email'), table_name='sys_user')
    op.drop_index(op.f('ix_sys_user_username'), table_name='sys_user')
    op.drop_table('sys_user')
    # ### end Alembic commands ###
